// English copy for the concept sheets (`art/*.svg`).
//
// The sheets are drawings with fixed layouts, so English is generated by
// swapping the Chinese strings in the built SVG rather than by re-laying out
// the drawings: every <text> element, the slider aria-labels on sheet 06, and
// the three script literals sheet 06's live readout rebuilds while dragging.
// Numbers come from `sim/` either way and are never touched.
//
//   node tools/gen-art.mjs --en        every sheet, Chinese + English side by side
//   node tools/gen-art.mjs 02 --en     only sheet 02
//
// A value is the English string, or `{ t, size }` where the English runs long
// and the element's font-size is pulled down to fit. Keep translations terse:
// most labels sit in fixed boxes drawn for Chinese, and English is wider.
// `node tools/sheet-png.mjs <nn>` rasterises a sheet so the fit can be looked at.
const EN = {
  '人/时': 'people/h',
  '支柱': 'Pillar',
  '每次加高 4 m': 'Raise by 4 m',
  '车站屋顶': 'Station roof',
  '薄顶棚，材质可涂刷': 'Thin canopy; paint its finish',
  '4 × 4 格': '4 × 4 cells',
  '纵向桁架顶棚，4/8/12 m，可涂刷': { t: 'Truss canopy; 4/8/12 m; paintable', size: 11 },
  '轨道': 'Track',
  '12 × 3 格': '12 × 3 cells',
  '开放轨道桥，延伸线路': 'Open viaduct; extend the line',
  '导向柱': 'Wayfinding pylon',
  '公交站': 'Bus stop',
  '4 × 2 格': '4 × 2 cells',
  '灯具': 'Lighting',
  '通风口': 'Vent',
  // 01 — isometric cutaway
  '地铁车站设计师': 'Metro Station Designer',
  'B1 站厅 · B2 站台。逐层建造，1 格 = 1 米。': 'B1 concourse · B2 platforms. Build floor by floor; 1 cell = 1 m.',
  '1  闸机：划出付费区，让人群有序进入': '1  Gates: fence the paid area for orderly entry',
  '2  扶梯与楼梯：连接站厅和站台': '2  Escalators & stairs: link concourse and platforms',
  '3  站台：等车、排队、上下车': '3  Platforms: waiting, queues, boarding',
  // 02 — vertical section
  '一座车站，叠了好几层': 'One station, stacked in layers',
  '街面出入口、地下站厅与三条线路，共用一组竖向交通。': 'Street entrances, an underground concourse and three lines share one vertical core.',
  '1 号线 · 高架站台': 'Line 1 · Elevated platforms',
  '从高架到地下，用换层设施连接。': 'Elevated to underground, joined by level changes.',
  'B2   2 号线站台': 'B2   Line 2 platforms',
  '地下站台': 'Underground',
  'B3   3 号线站台': 'B3   Line 3 platforms',
  '更深一层的站台': 'One level deeper',
  '地面': 'Street level',
  '站前广场，公交和出租车停靠，两个出入口': 'Station plaza: bus and taxi stops, two entrances',
  '地铁': 'METRO',
  '出入口': 'Entrances',
  '扶梯 ×3': 'Escalators ×3',
  '楼梯 ×2': 'Stairs ×2',
  '电梯': 'Lift',
  '竖向交通核：扶梯、楼梯、电梯各走各的运力': 'Vertical core: each mode carries its share',
  '闸机 · 付费区边界': 'Gates · paid-area boundary',
  '自动售票机': 'Ticket machines',
  '货架': 'Shelves',
  '自动售货机': 'Vending machines',
  '广告': 'Ads',
  'B1   水泥站厅': 'B1   Concrete concourse',
  '横断面 · 屏蔽门立在两侧站台边缘': 'Cross-section · screen doors on both platform edges',
  '+8 米': '+8 m',
  '0 米': '0 m',
  '-4 米': '-4 m',
  '-8 米': '-8 m',
  '-12 米': '-12 m',
  '扶梯、楼梯与电梯连接每一层。': 'Escalators, stairs and lifts join every level.',
  '乘客会走路、排队、刷卡和上车。': 'Passengers walk, queue, tap in and board.',
  '楼层越深，越需要照顾步行距离与换层队伍。': 'Deeper levels need kinder walks and transfer queues.',
  // 03 — block system
  '用一米方块，搭出自己的车站': 'Build your station from one-metre blocks',
  '拼出地板、墙和天花板，再用半墙、斜块与材质调整空间。': 'Snap together floors, walls and ceilings, then shape space with half-walls, wedges and finishes.',
  '1  每个面，单独换材质': '1  Each face takes its own finish',
  '顶面是地板，侧面是墙，底面是天花板。': 'Top is floor, sides are walls, bottom is ceiling.',
  '2  连着铺，拼成整片地面': '2  Lay them joined into whole floors',
  '相邻方块自动拼合，接缝处不会多出墙。': 'Neighbouring blocks merge; no stray walls at the seams.',
  '3  地板和墙，可以各有颜色': '3  Floors and walls can each have colours',
  '搪瓷板支持调色，做出车站自己的风格。': 'Enamel panels take any tint — give the station its own style.',
  '半墙': 'Half-wall',
  '上三角块': 'Upper wedge',
  '下三角块': 'Lower wedge',
  '半墙与斜块，让角落和边界更灵活。': 'Half-walls and wedges free up corners and edges.',
  '地面、墙面、天花板材质': 'Floor, wall and ceiling finishes',
  '花岗岩': 'Granite',
  '水泥': 'Concrete',
  '地砖': 'Floor tiles',
  '轨道床': 'Track bed',
  '覆土': 'Soil cover',
  '格栅天花': 'Grille ceiling',
  '金属吊顶': 'Metal ceiling',
  '钢板': 'Steel plate',
  '涂料': 'Paint',
  '拉丝不锈钢': 'Brushed steel',
  '土墙': 'Earth wall',
  '搪瓷板': 'Enamel panel',
  '轨道床和覆土不能通行，步行通路要铺可通行地面。': "Track beds and soil aren't walkable — pave routes with passable floors.",
  // 04 — module catalogue
  '可以放进车站的东西': 'Things to put in your station',
  '用闸机、扶梯和电梯组织客流，再用家具与标识装点车站。': 'Organise flow with gates, escalators and lifts; dress the station with furniture and signs.',
  '闸机': 'Gates',
  '进出各 25 人/分': '25/min each way',
  '围栏': 'Fences',
  '不通行，只围边界': 'Blocks passage, bounds areas',
  '售票机': 'Ticket machines',
  '1.5 张/分，队伍排这儿': '1.5 tickets/min — queues here',
  '自动贩卖机': 'Vending machines',
  '吸引乘客停留': 'Draws lingering passengers',
  '3 × 8 格': '3 × 8 cells',
  '每个出口单独设流量': 'Flow set per exit',
  '扶梯': 'Escalators',
  '1 × 7 格': '1 × 7 cells',
  '单向，75 人/分': 'One-way, 75/min',
  '2 × 2 格': '2 × 2 cells',
  '无障碍，每趟 15 人': 'Step-free, 15 per ride',
  '楼梯': 'Stairs',
  '上 25 / 下 33 人/分': 'Up 25 / down 33 per min',
  '座椅': 'Seats',
  '舒适度，可坐 1 人': 'Comfort, seats 1',
  '商铺货架，聚人': 'Shop shelves draw crowds',
  '办公桌': 'Desks',
  '办公位，吸引职员': 'Workspaces draw staff',
  '垃圾桶': 'Bins',
  '装点车站': 'Dresses the station',
  '灭火器': 'Fire extinguishers',
  '时钟': 'Clocks',
  '全站时间参照': 'Station-wide time reference',
  '广告牌': 'Billboards',
  '把人往商铺那边引': 'Pulls people toward the shops',
  '电视': 'TVs',
  '显示信息': 'Shows information',
  '指示牌': 'Signs',
  '导向，吊在头顶': 'Wayfinding, hung overhead',
  '门': 'Doors',
  '1.2 人/秒，关上挡路': '1.2 people/s; closed doors block',
  // 05 — trains and track
  '选列车，也在选站台的规模': 'Picking trains picks platform scale too',
  '四种车型按同一比例展示。编组越长，载客越多，也需要更长的站台。': 'All four types at one scale. Longer consists carry more — and need longer platforms.',
  'A 型': 'Type A',
  '编组 6–8 节': '6–8 cars per train',
  '6 节额定载客 1500 人': '6-car rated capacity: 1500',
  '6 节总长 132.0 米': '6-car total length: 132.0 m',
  'B 型': 'Type B',
  '编组 4–6 节': '4–6 cars per train',
  '6 节额定载客 1200 人': '6-car rated capacity: 1200',
  '6 节总长 117.0 米': '6-car total length: 117.0 m',
  'C 型': 'Type C',
  '6 节额定载客 1020 人': '6-car rated capacity: 1020',
  '6 节总长 114.0 米': '6-car total length: 114.0 m',
  'L 型': 'Type L',
  '6 节总长 100.8 米': '6-car total length: 100.8 m',
  '装不下的乘客会留在站台。看「滞留」，再调整车型或编组。': "Left-behind riders wait on the platform. Check 'stranded', then change type or consist.",
  '每条线路可单独设置供电、站台门、颜色和终点。': 'Each line sets its own power, screen doors, colour and termini.',
  // 06 — crowd demand
  '把早晚高峰，交给你的车站': 'Hand the rush hours to your station',
  '拖动蓝色营业边界与黄色高峰边界，试试车站能承受怎样的一天。': 'Drag the blue service edges and yellow peak edges to test what your station can take.',
  '营业 06:30–23:30 · 早高峰 07:30–09:00 · 晚高峰 17:30–19:00': 'Open 06:30–23:30 · AM peak 07:30–09:00 · PM peak 17:30–19:00',
  '1  调整高峰': '1  Shape the peaks',
  '拖动时间边界，改变高峰持续多久。': 'Drag the time edges to stretch the peaks.',
  '用下方滑块调整客流的强弱。': 'Use the sliders below for crowd strength.',
  '2  换一天试试': '2  Try another day',
  '选择工作日、周末或节假日，': 'Pick a workday, weekend or holiday,',
  '观察不同日子的客流压力。': "and feel each day's pressure.",
  '3  决定从哪里进站': '3  Choose where they enter',
  '每个出入口都能单独设置流量。': 'Every entrance sets its own flow.',
  '把人群分散到不同入口。': 'Spread crowds across entrances.',
  '增加客流后，运行车站：看看队伍先在哪里变长。': 'After adding demand, run the station and see where queues grow first.',
  // 07 — interface
  '边搭边看，哪里挤就改哪里': 'Build and watch; fix where it jams',
  '左边选工具，右边调设置，底栏看排队和滞留。': 'Tools left, settings right, queues and stranded along the bottom.',
  '1  建造': '1  Build',
  '选择方块和设备，逐层搭出车站。': 'Pick blocks and kit, raise the station floor by floor.',
  '2  调整': '2  Tune',
  '在信息栏设置出入口、线路和客流。': 'Set entrances, lines and demand in the info panel.',
  '3  观察': '3  Watch',
  '运行后看排队与滞留，再回到工地修改。': 'Run it, read queues and stranded, go back and rebuild.',
  // 09 — camera and views
  '几个视角，同一座站': 'Several views, one station',
  '转动、俯视或剖开同一座车站，找到被遮住的通路。': 'Orbit, top-down or cut open the same station to find hidden passages.',
  '建造视角': 'Build view',
  '转着看，安排设备与通路。': 'Orbit to place kit and passages.',
  '平面俯视': 'Top-down plan',
  '从上往下看，检查布局。': 'Look down from above to check the layout.',
  '剖切': 'Cutaway',
  '打开外壳，看清车站内部。': 'Open the shell to see inside.',
  '楼层剖面': 'Floor section',
  '检查楼层与换层设施的连接。': 'Check how floors join the level changes.',
  '平视': { t: 'Eye view', size: 10 },
  '站厅平视': 'Concourse eye view',
  '靠近乘客，看看空间的样子。': 'Get close to passengers and see the space.',
  '视图控件': 'View controls',
  '拖动立方体转视角，用高度条切换观察楼层。': 'Drag the cube to orbit; the height bar switches floors.',
  '看不清的地方，换个角度再看。': "Can't see it? Look from another angle.",
  // 11 — rolling stock 3D
  '四个等级，四种车体': 'Four classes, four bodies',
  '四种车型的外观。停靠后开门，乘客走进车厢。': "The four types' exteriors. Doors open at the stop; passengers step aboard.",
  '四个等级': 'Four classes',
  '开着门': 'Doors open',
  '车头': 'Cab',
  '车厢里能站人': 'Carriages hold standees',
  '乘客会进入车厢，不会停在车旁。': 'Passengers enter the car, never wait beside it.',
  '停靠后，乘客从车门上下车；': 'After the stop, passengers board and alight through the doors;',
  '站台门开口与车门位置对齐。': 'screen-door openings line up with the train doors.',
  // 12 — platform doors and flow
  '让上下车的人，各有一条路': 'Boarding and alighting each get a path',
  '车门两侧排队，中间留给下车乘客。观察人群怎样通过站台。': 'Queue each side of the doors, keep the middle for alighting. Watch crowds cross the platform.',
  'A.  上车时序（平面）': 'A. Boarding sequence (plan)',
  '列车停稳后开门，乘客从中间下车，从两侧上车。': 'Doors open at the stop: alight through the middle, board from the sides.',
  '↑ 通往站厅   扶梯 + 楼梯 + 电梯   （出站走这边）': {
    t: '↑ To the concourse — escalators + stairs + lifts (exit here)',
    size: 10,
  },
  '下车': 'Alighting',
  '站台平面': 'Platform plan',
  '排队通道': 'Queue lanes',
  'B.  列车停靠（立面）': 'B. Train at the platform (elevation)',
  '列车停靠在站台边缘，乘客从车门上下车。': 'The train stops at the platform edge; passengers use the doors.',
  '车门与站台门对齐，乘客在此上下车。': 'Doors line up with the screen doors — board and alight here.',
  'C.  乘客自己找路': 'C. Passengers find their own way',
  '连接车门、换层设施和出口，乘客会自己选择通路。': 'Join doors, level changes and exits; passengers pick their own routes.',
  '车门': 'Train doors',
  '让开门口': 'Keep doors clear',
  '站台': 'Platform',
  '走下车路径': 'Alighting paths',
  '步行': 'Walk',
  '导向': 'Wayfinding',
  '标识帮助认路': 'Signs guide them',
  '读取': 'Read',
  '竖向': 'Vertical',
  '扶梯 / 楼梯 / 电梯': { t: 'Escalators / stairs / lifts', size: 8.8 },
  '站厅': 'Concourse',
  '跟着黄色导向带': 'Yellow guide strips',
  '从队尾加入通道': 'Join lanes from the tail',
  '出口': 'Exits',
  '地面出口，进出可设': 'Street exits, set flows',
  '到达': 'Arrive',
  '走出车站': 'Leave the station',
  '完成': 'Done',
  '队伍太长，乘客会尝试改道。留出更多可选通路。': 'Long queues make riders reroute. Leave more alternatives.',
  '轮椅乘客需要电梯或坡道，换层时也要照顾他们。': 'Wheelchair users need lifts or ramps — on every level change.',
  // 13 — two-line interchange
  '一条在街上，一条在街下': 'One line above the street, one below',
  '街面出入口、B1 站厅、B2 岛式站台，与高架线路叠在一起。': 'Street entrances, a B1 concourse and a B2 island platform, stacked with the elevated line.',
  '换乘，要走过这些空间': 'Transfer means crossing these spaces',
  '1  高架站台': '1  Elevated platforms',
  '地面以上的 1 号线': 'Line 1 above the ground',
  '↓  换层': '↓ Change levels',
  '2  B1 站厅': '2  B1 concourse',
  '在这里分流，连接不同楼层': 'Split flows here, join the levels',
  '3  B2 岛式站台': '3  B2 island platform',
  '地下的 2 号线': 'Line 2 underground',
  '扶梯、楼梯与电梯的布局，': 'How escalators, stairs and lifts are laid out',
  '决定换乘要走多远、等多久。': 'decides transfer walks and waits.',
  '观察换层口的队伍，再调整通路。': 'Watch queues at the level changes, then adjust.',
};

// Sheet 06's slider handles expose Chinese aria-labels (attributes, not <text>).
const EN_ATTR = {
  '早高峰量': 'AM peak volume',
  '晚高峰量': 'PM peak volume',
  '波形陡峭度': 'Peak width',
  '开站时间': 'Opens',
  '关站时间': 'Closes',
  '早高峰开始': 'AM peak starts',
  '早高峰结束': 'AM peak ends',
  '晚高峰开始': 'PM peak starts',
  '晚高峰结束': 'PM peak ends',
};

// Sheet 06's live readout rebuilds its line from these literals while dragging.
const EN_SCRIPT = {
  '营业 ': 'Open ',
  '早高峰 ': 'AM peak ',
  '晚高峰 ': 'PM peak ',
};

const CJK = /[㐀-䶿一-鿿豈-﫿]+/;

/** English copy can use plain `&`; SVG text and attributes cannot. */
const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/**
 * Rewrite a generated (Chinese) sheet in English. Returns the rewritten SVG
 * plus every Chinese string with no table entry, so gaps fail loudly instead
 * of shipping half-translated.
 */
export function toEnglish(svg) {
  const missing = new Set();
  // Whole <text> contents first (attributes preserved untouched).
  let sizePatches = [];
  let out = svg.replace(/<text\b([^>]*)>([^<]*)<\/text>/g, (m, attrs, inner) => {
    const patch = {};
    let next = inner;
    if (CJK.test(inner)) {
      if (Object.hasOwn(EN, inner)) {
        const v = EN[inner];
        if (typeof v === 'string') next = esc(v);
        else {
          next = esc(v.t);
          patch.size = v.size;
        }
      } else {
        const t = inner.trim();
        if (Object.hasOwn(EN, t)) {
          const v = EN[t];
          const body = esc(typeof v === 'string' ? v : v.t);
          if (typeof v !== 'string') patch.size = v.size;
          const i = inner.indexOf(t);
          next = inner.slice(0, i) + body + inner.slice(i + t.length);
        } else missing.add(inner);
      }
    }
    let a = attrs;
    if (patch.size) {
      a = /font-size="[\d.]+"/.test(attrs)
        ? attrs.replace(/font-size="[\d.]+"/, `font-size="${patch.size}"`)
        : `${attrs} font-size="${patch.size}"`;
      sizePatches.push(next);
    }
    return `<text${a}>${next}</text>`;
  });
  // aria-labels on the interactive handles.
  out = out.replace(/aria-label="([^"]*)"/g, (m, v) =>
    CJK.test(v) && Object.hasOwn(EN_ATTR, v) ? `aria-label="${esc(EN_ATTR[v])}"` : (CJK.test(v) && missing.add(`aria:${v}`), m),
  );
  // Script literals the live readout rebuilds from (longest first).
  for (const k of Object.keys(EN_SCRIPT).sort((a, b) => b.length - a.length)) {
    out = out.split(k).join(EN_SCRIPT[k]);
  }
  // Anything Chinese left is either a gap or a false friend — report it.
  for (const m of out.matchAll(/<text\b[^>]*>([^<]*)<\/text>/g)) {
    if (CJK.test(m[1]) && !Object.hasOwn(EN, m[1].trim())) missing.add(m[1]);
  }
  return { svg: out, missing: [...missing] };
}

/** Every Chinese string across the built sheets, for coverage checks. */
export function auditZh(svg) {
  const found = new Set();
  for (const m of svg.matchAll(/<text\b[^>]*>([^<]*)<\/text>/g)) {
    if (CJK.test(m[1])) found.add(m[1].trim());
  }
  for (const m of svg.matchAll(/aria-label="([^"]*)"/g)) {
    if (CJK.test(m[1])) found.add(`aria:${m[1]}`);
  }
  return [...found];
}
